### ISSUE TITLE
Can I archive this repo?

### ISSUE THREAD

**Issue by ElizabethN** [badging/template-submit#2]
@thecraftman This is another repo that seems like it was being used at the creation of the Badging program, but it is pretty empty and hasn't seen activity for a few years. Does this information exist elsewhere? Would it be ok if I archived this repo? Just trying to clean up some of the repos and docs for badging. Thank you! :pray:

**Comment by thecraftman** [comment]
@ElizabethN thank you. Yes you can archive it. We aren't using it anymore. Thanks for bringing this up. Let me know if you have any questions.

**Comment by ElizabethN** [comment]
@thecraftman thank you so much! :pray:
